AWSTemplateFormatVersion: 2010-09-09
Description: |
  Create CloudFromationRole

Resources:
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudformation-service-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub cloudformation-policy
          PolicyDocument: !Sub |
            {
                "Version": "2012-10-17",
                "Statement": [{
                        "Effect": "Allow",
                        "Action": [ "*" ],
                        "Resource": "*"
                }]
            }
        - PolicyName: !Sub cloudformation-trust
          PolicyDocument: !Sub |
            {
                "Version": "2012-10-17",
                "Statement": [{
                    "Effect": "Allow",
                    "Action": [
                        "iam:GetRole",
                        "iam:PassRole"
                    ],
                    "Resource": "arn:aws:iam::${AWS::AccountId}:role/*"
                }]
            }

Outputs:
  CloudFormationServiceRoleArn:
    Description: The CodePipeline service
    Value: !GetAtt CloudFormationRole.Arn
    Export:
      Name: CloudFormationServiceRole

