AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Create ConcourseSecretsManagerRole for concourse

Resources:
  ConcourseSecretsManagerRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: ConcourseSecretsManagerRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - "ec2.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      Path: "/"
  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "AllowAccessToSecretManagerParameters"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action: "secretsmanager:ListSecrets"
          Resource: "*"
        - Effect: "Allow"
          Action:
          - "secretsmanager:GetSecretValue"
          - "secretsmanager:DescribeSecret"
          Resource:
          - "arn:aws:secretsmanager:::secret:/concourse/*"
      Roles:
      - !Ref ConcourseSecretsManagerRole
  RootInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
      - !Ref ConcourseSecretsManagerRole