AWSTemplateFormatVersion: 2010-09-09
Description: Example template with Customer Master Key and S3 bucket

Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${CMKAlias}'
              SSEAlgorithm: 'aws:kms'

  CMKAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: 'alias/test/cmk'
      TargetKeyId: !Ref CMK

  CMK:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: 'My CMK'
      Enabled: True
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Allow root IAM'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:*'
            Resource: '*'

Outputs:
  CMKId:
    Value: !Ref CMK
  CMKArn:
    Value: !GetAtt CMK.Arn
  CMKAliasArn:
    Value: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${CMKAlias}'
  Bucket:
    Value: !Ref Bucket