AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Create DataPipelineDefaultRole and DataPipelineDefaultResourceRole for datapipeline

Resources:
  DataPipelineDefaultRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: DataPipelineDefaultRole
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AWSDataPipelineRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - "elasticmapreduce.amazonaws.com"
            - "datapipeline.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      Path: "/"

  DataPipelineDefaultResourceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: DataPipelineDefaultResourceRole
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforDataPipelineRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - "ec2.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      Path: "/"

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: DataPipelineDefaultResourceRole
      Path: "/"
      Roles:
      - Ref: DataPipelineDefaultResourceRole