AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Data pipeline that copies DynamoDB source table to DynamoDB destination table using S3 bucket as a temporal storage

Parameters:
  ActivateDataPipeline:
    AllowedValues:
      - "true"
      - "false"
    Type: String
    Description: Activate Data Pipeline
    Default: "true"

  FlowCommand:
    Type: String
    Description: Flow command to execute
    Default: "flow --version"

  FlowVersion:
    Type: String
    Description: Flow version
    Default: "latest"

  InstanceType:
    Type: String
    Description: Instance type for ec2
    Default: "t2.nano"

Resources:
  LogsS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  FlowTooling:
    Type: AWS::DataPipeline::Pipeline
    Properties:
      Name: "flow-tooling"
      Description: "Pipeline to flow tooling"
      Activate: !Ref ActivateDataPipeline
      ParameterObjects:
        - Id: "myLogsS3"
          Attributes:
            - Key: "description"
              StringValue: "S3 logs bucket"
            - Key: "type"
              StringValue: "AWS::S3::ObjectKey"
            - Key: "default"
              StringValue: !Sub "s3://${LogsS3Bucket}"

      PipelineObjects:
        - Id: "Default"
          Name: "Default"
          Fields:
            - Key: "type"
              StringValue: "Default"
            - Key: "scheduleType"
              StringValue: "ondemand"
            - Key: "failureAndRerunMode"
              StringValue: "CASCADE"
            - Key: "role"
              StringValue: "DataPipelineDefaultRole"
            - Key: "resourceRole"
              StringValue: "DataPipelineDefaultResourceRole"
            - Key: "pipelineLogUri"
              StringValue: "#{myLogsS3}"

        - Id: "FlowEC2"
          Name: "FlowEC2"
          Fields:
            - Key: "terminateAfter"
              StringValue: "1 Hour"
            - Key: "actionOnTaskFailure"
              StringValue: "retryAll"
            - Key: "actionOnResourceFailure"
              StringValue: "retryAll"
            - Key: "maximumRetries"
              StringValue: "2"
            - Key: "instanceType"
              StringValue: "t2.micro"
            - Key: "type"
              StringValue: "Ec2Resource"

        - Id: "InstallFlow"
          Name: "InstallFlow"
          Fields:
            - Key: "runsOn"
              RefValue: "FlowEC2"
            - Key: "type"
              StringValue: "ShellCommandActivity"
            - Key: "command"
              StringValue: !Sub "(curl https://raw.githubusercontent.com/flow-lab/flow/master/bin/get-flow.sh --output get-flow.sh --fail) && (chmod +x get-flow.sh) && (./get-flow.sh $FlowVersion && sudo mv flow /usr/bin)"

        - Id: "ExecuteFlow"
          Name: "ExecuteFlow"
          Fields:
            - Key: "dependsOn"
              RefValue: "InstallFlow"
            - Key: "runsOn"
              RefValue: "FlowEC2"
            - Key: "type"
              StringValue: "ShellCommandActivity"
            - Key: "command"
              StringValue: !Sub "${FlowCommand}"

Outputs:
  LogsS3Bucket:
    Value: !Ref LogsS3Bucket
    Description: Name of log S3 bucket
  FlowToolingDataPipeline:
    Value: !Ref FlowTooling
    Description: Pipeline ID